// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY9dRjZJJpccEI6ed8lJEiv9lH0zB2Mqs',
    appId: '1:661063287878:android:b2a51951811e5c5e473647',
    messagingSenderId: '661063287878',
    projectId: 'chat-app-9bbff',
    storageBucket: 'chat-app-9bbff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwQct0wXy7ONbJtwS08SAxiI1dn_5GAxA',
    appId: '1:661063287878:ios:7c05d79bcc58cc2a473647',
    messagingSenderId: '661063287878',
    projectId: 'chat-app-9bbff',
    storageBucket: 'chat-app-9bbff.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Lmja4XH1eYnbgn4hy0CcLx8Nzituf_A',
    appId: '1:661063287878:web:0b9d95dfba6a2862473647',
    messagingSenderId: '661063287878',
    projectId: 'chat-app-9bbff',
    authDomain: 'chat-app-9bbff.firebaseapp.com',
    storageBucket: 'chat-app-9bbff.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwQct0wXy7ONbJtwS08SAxiI1dn_5GAxA',
    appId: '1:661063287878:ios:7c05d79bcc58cc2a473647',
    messagingSenderId: '661063287878',
    projectId: 'chat-app-9bbff',
    storageBucket: 'chat-app-9bbff.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Lmja4XH1eYnbgn4hy0CcLx8Nzituf_A',
    appId: '1:661063287878:web:487afe14844b3913473647',
    messagingSenderId: '661063287878',
    projectId: 'chat-app-9bbff',
    authDomain: 'chat-app-9bbff.firebaseapp.com',
    storageBucket: 'chat-app-9bbff.appspot.com',
  );

}